# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\serviceLoginApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(859, 455)
        Form.setStyleSheet("background-color: #ABCDEF;\n"
"border: 0;\n"
"border-radius: 0;\n"
"color: white;")
        self.verticalWidget = QtWidgets.QWidget(Form)
        self.verticalWidget.setGeometry(QtCore.QRect(310, 70, 221, 271))
        self.verticalWidget.setStyleSheet("")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Login = QtWidgets.QLineEdit(self.verticalWidget)
        self.Login.setStyleSheet("* {\n"
"background-color: #7FB9EB;\n"
"border: 1px solid black;\n"
"border-radius: 3px;\n"
"height: 30px;\n"
"}")
        self.Login.setMaxLength(30)
        self.Login.setObjectName("Login")
        self.verticalLayout.addWidget(self.Login)
        self.Password = QtWidgets.QLineEdit(self.verticalWidget)
        self.Password.setStyleSheet("* {\n"
"background-color: #7FB9EB;\n"
"border: 1px solid black;\n"
"border-radius: 3px;\n"
"height: 30px;\n"
"}")
        self.Password.setMaxLength(25)
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.verticalLayout.addWidget(self.Password)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.signup = QtWidgets.QPushButton(self.verticalWidget)
        self.signup.setEnabled(False)
        self.signup.setStyleSheet("* {\n"
"background-color: #7FB9EB;\n"
"border: 1px solid black;\n"
"border-radius: 3px;\n"
"height: 40px;\n"
"}\n"
"\n"
"*:hover {\n"
"background-color: #AAD0F3;\n"
"color: black;\n"
"}\n"
"\n"
"*:disabled,\n"
"*[disabled]{\n"
"  background-color: #CEDFF3;\n"
"  color: #363636;\n"
"}")
        self.signup.setObjectName("signup")
        self.verticalLayout.addWidget(self.signup)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(30, 10, 70, 70))
        self.frame.setStyleSheet("* {\n"
"    image: url(:/LogoType/designe/LogoType.png);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.Login, self.Password)
        Form.setTabOrder(self.Password, self.signup)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Login.setPlaceholderText(_translate("Form", "Логин"))
        self.Password.setPlaceholderText(_translate("Form", "Пароль"))
        self.signup.setText(_translate("Form", "Войти"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
