# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\serviceClientApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(859, 455)
        Form.setStyleSheet("background-color: #89A6D2;\n"
"border: 0;\n"
"border-radius: 0;\n"
"color: white;")
        self.header = QtWidgets.QFrame(Form)
        self.header.setGeometry(QtCore.QRect(0, 0, 871, 41))
        self.header.setStyleSheet("* {\n"
"    background-color: #CDD7E4;\n"
"}")
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.Applications = QtWidgets.QPushButton(self.header)
        self.Applications.setEnabled(True)
        self.Applications.setGeometry(QtCore.QRect(20, 10, 75, 23))
        self.Applications.setStyleSheet("\n"
"* {\n"
"background-color: #7FB9EB;\n"
"width: 80px;\n"
"height: 40px;\n"
"}\n"
"\n"
"*:hover {\n"
"background-color: #AAD0F3;\n"
"color: black;\n"
"}\n"
"\n"
"*:disabled,\n"
"*[disabled]{\n"
"  background-color: #CEDFF3;\n"
"  color: #363636;\n"
"}")
        self.Applications.setObjectName("Applications")
        self.Customers = QtWidgets.QPushButton(self.header)
        self.Customers.setEnabled(False)
        self.Customers.setGeometry(QtCore.QRect(120, 10, 75, 23))
        self.Customers.setStyleSheet("\n"
"* {\n"
"background-color: #7FB9EB;\n"
"width: 80px;\n"
"height: 40px;\n"
"}\n"
"\n"
"*:hover {\n"
"background-color: #AAD0F3;\n"
"color: black;\n"
"}\n"
"\n"
"*:disabled,\n"
"*[disabled]{\n"
"  background-color: #CEDFF3;\n"
"  color: #363636;\n"
"}")
        self.Customers.setObjectName("Customers")
        self.exit = QtWidgets.QPushButton(self.header)
        self.exit.setGeometry(QtCore.QRect(740, 9, 75, 23))
        self.exit.setStyleSheet("* {\n"
"color: white;\n"
"}\n"
"\n"
"*:hover {\n"
"    color: red;\n"
"}")
        self.exit.setObjectName("exit")
        self.logo = QtWidgets.QFrame(self.header)
        self.logo.setGeometry(QtCore.QRect(820, 6, 30, 30))
        self.logo.setStyleSheet("* {\n"
"    image: url(:/LogoType/designe/LogoType.png);\n"
"}")
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.Field = QtWidgets.QTreeWidget(Form)
        self.Field.setGeometry(QtCore.QRect(0, 40, 861, 361))
        self.Field.setStyleSheet("* {\n"
"color: black;\n"
"}")
        self.Field.setObjectName("Field")
        self.CarNumber = QtWidgets.QLineEdit(Form)
        self.CarNumber.setGeometry(QtCore.QRect(10, 416, 111, 32))
        self.CarNumber.setStyleSheet("* {\n"
"background-color: #7FB9EB;\n"
"height: 30px;\n"
"}")
        self.CarNumber.setObjectName("CarNumber")
        self.assept = QtWidgets.QPushButton(Form)
        self.assept.setEnabled(False)
        self.assept.setGeometry(QtCore.QRect(135, 416, 101, 31))
        self.assept.setStyleSheet("\n"
"* {\n"
"background-color: #7FB9EB;\n"
"width: 80px;\n"
"height: 40px;\n"
"}\n"
"\n"
"*:hover {\n"
"background-color: #AAD0F3;\n"
"color: black;\n"
"}\n"
"\n"
"*:disabled,\n"
"*[disabled]{\n"
"  background-color: #CEDFF3;\n"
"  color: #363636;\n"
"}")
        self.assept.setObjectName("assept")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Applications.setText(_translate("Form", "Заявки"))
        self.Customers.setText(_translate("Form", "Клиенты"))
        self.exit.setText(_translate("Form", "Выход"))
        self.Field.headerItem().setText(0, _translate("Form", "Марка машины"))
        self.Field.headerItem().setText(1, _translate("Form", "Номер машины"))
        self.Field.headerItem().setText(2, _translate("Form", "ФИО"))
        self.Field.headerItem().setText(3, _translate("Form", "Поломка"))
        self.CarNumber.setPlaceholderText(_translate("Form", "Номер машины"))
        self.assept.setText(_translate("Form", "Принять"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
